version: '3'

services:
  db:
    image: mysql:latest
    container_name: prj_sell_web_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: my_database
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: prj_sell_web_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: admin
    ports:
      - "8081:80"
